const querySelector = document.querySelector('.title-1')
console.dir(querySelector)
const querySelectorAll = document.querySelectorAll('h2')
console.dir(querySelectorAll)
const className = document.getElementsByClassName('title-1')
console.dir(className)
const tagName = document.getElementsByTagName('h2')
console.dir(tagName)